# Generated by Django 5.1.4 on 2025-02-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
